"""
Email delivery for Sago Brief Pipeline.

Sends the generated PDF brief to all meeting guests via Gmail API,
and a confirmation to the meeting organizer.
"""

import os
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

_HERE = os.path.dirname(os.path.abspath(__file__))
_TOKEN_PATH = os.path.join(_HERE, "sago_cal", "token.json")
_SCOPES = [
    "https://www.googleapis.com/auth/calendar.readonly",
    "https://www.googleapis.com/auth/gmail.send",
]


def _get_gmail_service():
    creds = Credentials.from_authorized_user_file(_TOKEN_PATH, _SCOPES)
    return build("gmail", "v1", credentials=creds)


def _send_message(service, message):
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
    service.users().messages().send(userId="me", body={"raw": raw}).execute()


def send_brief_to_guests(pdf_path: str, recipients: list, meeting_title: str, target: str):
    """Send the brief PDF to all meeting guests."""
    service = _get_gmail_service()
    pdf_path = Path(pdf_path)

    for person in recipients:
        msg = MIMEMultipart()
        msg["To"] = person["email"]
        msg["Subject"] = f"Sago Brief: {target} — {meeting_title}"

        name = person.get("name") or person["email"].split("@")[0]
        body = f"""Hi {name},

Please find attached your Sago brief for the upcoming meeting: {meeting_title}.

This brief was automatically generated by Sago based on your calendar invite.

Best,
Sago
"""
        msg.attach(MIMEText(body, "plain"))

        with open(pdf_path, "rb") as f:
            pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
            pdf_attachment.add_header(
                "Content-Disposition", "attachment", filename=pdf_path.name
            )
            msg.attach(pdf_attachment)

        _send_message(service, msg)
        print(f"  Brief sent to: {person['email']}")


def send_confirmation_to_organizer(organizer_email: str, recipients: list, meeting_title: str, target: str):
    """Send a confirmation email to the meeting organizer."""
    service = _get_gmail_service()

    recipient_list = "\n".join(f"  - {p['email']}" for p in recipients)

    msg = MIMEMultipart()
    msg["To"] = organizer_email
    msg["Subject"] = f"Sago Brief Delivered: {target}"
    body = f"""Hi,

A Sago brief for "{target}" has been generated and sent to the following attendees of "{meeting_title}":

{recipient_list}

Best,
Sago
"""
    msg.attach(MIMEText(body, "plain"))
    _send_message(service, msg)
    print(f"  Confirmation sent to organizer: {organizer_email}")
